<?php

return [
    'default' => '+972',
    'list' => [
        ['iso2' => 'PS', 'name' => 'فلسطين', 'dial_code' => '+972'],
        ['iso2' => 'JO', 'name' => 'الأردن', 'dial_code' => '+962'],
        ['iso2' => 'SA', 'name' => 'السعودية', 'dial_code' => '+966'],
        ['iso2' => 'AE', 'name' => 'الإمارات', 'dial_code' => '+971'],
        ['iso2' => 'EG', 'name' => 'مصر', 'dial_code' => '+20'],
        ['iso2' => 'IQ', 'name' => 'العراق', 'dial_code' => '+964'],
        ['iso2' => 'SY', 'name' => 'سوريا', 'dial_code' => '+963'],
        ['iso2' => 'LB', 'name' => 'لبنان', 'dial_code' => '+961'],
        ['iso2' => 'QA', 'name' => 'قطر', 'dial_code' => '+974'],
        ['iso2' => 'KW', 'name' => 'الكويت', 'dial_code' => '+965'],
        ['iso2' => 'BH', 'name' => 'البحرين', 'dial_code' => '+973'],
        ['iso2' => 'OM', 'name' => 'عمان', 'dial_code' => '+968'],
        ['iso2' => 'TR', 'name' => 'تركيا', 'dial_code' => '+90'],
        ['iso2' => 'US', 'name' => 'United States', 'dial_code' => '+1'],
        ['iso2' => 'CA', 'name' => 'Canada', 'dial_code' => '+1'],
        ['iso2' => 'GB', 'name' => 'United Kingdom', 'dial_code' => '+44'],
        ['iso2' => 'FR', 'name' => 'France', 'dial_code' => '+33'],
        ['iso2' => 'DE', 'name' => 'Germany', 'dial_code' => '+49'],
        ['iso2' => 'IT', 'name' => 'Italy', 'dial_code' => '+39'],
        ['iso2' => 'ES', 'name' => 'Spain', 'dial_code' => '+34'],
        ['iso2' => 'NL', 'name' => 'Netherlands', 'dial_code' => '+31'],
        ['iso2' => 'SE', 'name' => 'Sweden', 'dial_code' => '+46'],
        ['iso2' => 'NO', 'name' => 'Norway', 'dial_code' => '+47'],
        ['iso2' => 'DK', 'name' => 'Denmark', 'dial_code' => '+45'],
        ['iso2' => 'CH', 'name' => 'Switzerland', 'dial_code' => '+41'],
        ['iso2' => 'RU', 'name' => 'Russia', 'dial_code' => '+7'],
        ['iso2' => 'IN', 'name' => 'India', 'dial_code' => '+91'],
        ['iso2' => 'PK', 'name' => 'Pakistan', 'dial_code' => '+92'],
        ['iso2' => 'BD', 'name' => 'Bangladesh', 'dial_code' => '+880'],
        ['iso2' => 'ID', 'name' => 'Indonesia', 'dial_code' => '+62'],
        ['iso2' => 'MY', 'name' => 'Malaysia', 'dial_code' => '+60'],
        ['iso2' => 'SG', 'name' => 'Singapore', 'dial_code' => '+65'],
        ['iso2' => 'CN', 'name' => 'China', 'dial_code' => '+86'],
        ['iso2' => 'JP', 'name' => 'Japan', 'dial_code' => '+81'],
        ['iso2' => 'KR', 'name' => 'South Korea', 'dial_code' => '+82'],
        ['iso2' => 'AU', 'name' => 'Australia', 'dial_code' => '+61'],
        ['iso2' => 'NZ', 'name' => 'New Zealand', 'dial_code' => '+64'],
        ['iso2' => 'BR', 'name' => 'Brazil', 'dial_code' => '+55'],
        ['iso2' => 'MX', 'name' => 'Mexico', 'dial_code' => '+52'],
        ['iso2' => 'ZA', 'name' => 'South Africa', 'dial_code' => '+27'],
    ],
];
