<?php

namespace App\Http\Controllers;

use App\Models\HrTask;
use App\Models\OperationalSetting;
use App\Models\SupportTicket;
use App\Models\SupportTicketMessage;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class SupportQuickTicketController extends Controller
{
    public function store(Request $request): JsonResponse
    {
        $data = $request->validate([
            'subject' => 'nullable|string|max:255',
            'category' => 'nullable|string|max:100',
            'priority' => 'nullable|in:low,normal,high,urgent',
            'message' => 'required|string|max:5000',
            'page_url' => 'nullable|string|max:2000',
            'page_title' => 'nullable|string|max:255',
            'capture_path' => 'nullable|string|max:255',
            'capture_url' => 'nullable|string|max:2000',
            'capture_hash' => 'nullable|string|max:128',
            'capture_signature' => 'nullable|string|max:255',
            'capture_timestamp' => 'nullable|string|max:100',
        ]);

        $isAdmin = (bool) optional(auth()->user())->is_admin;

        if (!$isAdmin && !OperationalSetting::getValue('support_ticket_enabled', true)) {
            return response()->json([
                'ok' => false,
                'message' => 'Support tickets are disabled.',
            ], 403);
        }

        $priority = $data['priority'] ?? 'high';
        $category = 'other';
        if (!empty($data['category']) && array_key_exists($data['category'], SupportTicket::CATEGORY)) {
            $category = $data['category'];
        }

        $subject = trim((string) ($data['subject'] ?? ''));
        if ($subject === '') {
            $subject = 'بلاغ دعم تلقائي - ' . ($data['page_title'] ?? 'بدون عنوان');
        }

        $lines = [trim((string) $data['message'])];
        if (!empty($data['page_url'])) {
            $lines[] = 'رابط الصفحة: ' . $data['page_url'];
        }
        if (!empty($data['capture_url'])) {
            $lines[] = 'رابط لقطة الشاشة: ' . $data['capture_url'];
        }
        if (!empty($data['capture_hash'])) {
            $lines[] = 'SHA256: ' . $data['capture_hash'];
        }
        if (!empty($data['capture_signature'])) {
            $lines[] = 'Signature: ' . $data['capture_signature'];
        }
        if (!empty($data['capture_timestamp'])) {
            $lines[] = 'Server Time: ' . $data['capture_timestamp'];
        }

        $description = implode("\n", array_filter($lines));

        if ($isAdmin && Gate::allows('order_create')) {
            $ticket = SupportTicket::create([
                'user_id' => auth()->id(),
                'subject' => $subject,
                'category' => $category,
                'priority' => $priority,
                'status' => 'open',
                'source' => 'admin',
                'requester_department' => 'operations',
                'request_context' => 'other',
                'description' => $description,
                'notes' => 'Generated by quick support workflow.',
                'last_reply_at' => now(),
            ]);

            SupportTicketMessage::create([
                'support_ticket_id' => $ticket->id,
                'user_id' => auth()->id(),
                'sender_type' => 'agent',
                'is_internal' => false,
                'message' => $description,
            ]);

            try {
                HrTask::create([
                    'title' => 'متابعة تذكرة دعم #' . $ticket->id,
                    'description' => $ticket->subject,
                    'module' => 'support',
                    'task_type' => 'ticket_follow_up',
                    'priority' => $ticket->priority === 'urgent' ? 'urgent' : 'normal',
                    'status' => 'open',
                    'assigned_user_id' => $ticket->assigned_to,
                    'created_by' => auth()->id(),
                    'related_type' => SupportTicket::class,
                    'related_id' => $ticket->id,
                    'due_at' => now()->addHours(2),
                ]);
            } catch (\Throwable $e) {
                // Keep quick ticket creation resilient if optional HR task flow fails.
            }

            return response()->json([
                'ok' => true,
                'ticket_id' => $ticket->id,
                'ticket_number' => $ticket->ticket_number,
                'show_url' => route('admin.support-tickets.show', $ticket),
            ]);
        }

        $ticket = SupportTicket::create([
            'user_id' => auth()->id(),
            'subject' => $subject,
            'category' => $category,
            'priority' => $priority,
            'status' => 'open',
            'source' => 'customer',
            'description' => $description,
            'last_reply_at' => now(),
        ]);

        SupportTicketMessage::create([
            'support_ticket_id' => $ticket->id,
            'user_id' => auth()->id(),
            'sender_type' => 'customer',
            'message' => $description,
        ]);

        return response()->json([
            'ok' => true,
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'show_url' => route('user.support-tickets.show', $ticket),
        ]);
    }
}
